/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bacanto,Charles Dominique A.
 */
import java.awt.event.KeyEvent;

public class BCalFrame extends javax.swing.JFrame {
    double firstNum;
    double secondNum;
    double result;
    String operation;
    /**
     * Creates new form BCalFrame
     */
    
    public void enable(){
        btnOn.setEnabled(true);
        screenDisplay.setEnabled(true);
        btnAdditionOp.setEnabled(true);
        btnSubtractionOp.setEnabled(true);
        btnMultiplicationOp.setEnabled(true);
        btnDivisionOP.setEnabled(true);
        btnPlusMinus.setEnabled(true);
        btnClearOp.setEnabled(true);
        btnDeciPoint.setEnabled(true);
        btnDelOp.setEnabled(true);
        btnEqualOp.setEnabled(true);
        btnNine.setEnabled(true);
        btnEight.setEnabled(true);
        btnSeven.setEnabled(true);
        btnSix.setEnabled(true);
        btnFive.setEnabled(true);
        btnFour.setEnabled(true);
        btnThree.setEnabled(true);
        btnTwo.setEnabled(true);
        btnOne.setEnabled(true);
        btnZero.setEnabled(true);
    }
    public void disable(){
         btnOn.setEnabled(true);
        screenDisplay.setEnabled(false);
        btnAdditionOp.setEnabled(false);
        btnSubtractionOp.setEnabled(false);
        btnMultiplicationOp.setEnabled(false);
        btnDivisionOP.setEnabled(false);
        btnPlusMinus.setEnabled(false);
        btnClearOp.setEnabled(false);
        btnDeciPoint.setEnabled(false);
        btnDelOp.setEnabled(false);
        btnEqualOp.setEnabled(false);
        btnNine.setEnabled(false);
        btnEight.setEnabled(false);
        btnSeven.setEnabled(false);
        btnSix.setEnabled(false);
        btnFive.setEnabled(false);
        btnFour.setEnabled(false);
        btnThree.setEnabled(false);
        btnTwo.setEnabled(false);
        btnOne.setEnabled(false);
        btnZero.setEnabled(false);
    }
    public BCalFrame() {
        initComponents();
        
        btnOn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        screenDisplay = new javax.swing.JTextField();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnDivisionOP = new javax.swing.JButton();
        btnMultiplicationOp = new javax.swing.JButton();
        btnSubtractionOp = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnDeciPoint = new javax.swing.JButton();
        btnEqualOp = new javax.swing.JButton();
        btnAdditionOp = new javax.swing.JButton();
        btnClearOp = new javax.swing.JButton();
        btnDelOp = new javax.swing.JButton();
        btnOn = new javax.swing.JRadioButton();
        btnOff = new javax.swing.JRadioButton();
        btnPlusMinus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BacantoName = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        screenDisplay.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        screenDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        screenDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screenDisplayActionPerformed(evt);
            }
        });
        screenDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                screenDisplayKeyTyped(evt);
            }
        });

        btnOne.setBackground(new java.awt.Color(204, 204, 204));
        btnOne.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnOne.setText("1");
        btnOne.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });

        btnTwo.setBackground(new java.awt.Color(204, 204, 204));
        btnTwo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnTwo.setText("2");
        btnTwo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });

        btnThree.setBackground(new java.awt.Color(204, 204, 204));
        btnThree.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnThree.setText("3");
        btnThree.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });

        btnFour.setBackground(new java.awt.Color(204, 204, 204));
        btnFour.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnFour.setText("4");
        btnFour.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });

        btnFive.setBackground(new java.awt.Color(204, 204, 204));
        btnFive.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnFive.setText("5");
        btnFive.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });

        btnSix.setBackground(new java.awt.Color(204, 204, 204));
        btnSix.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnSix.setText("6");
        btnSix.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });

        btnSeven.setBackground(new java.awt.Color(204, 204, 204));
        btnSeven.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnSeven.setText("7");
        btnSeven.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSeven.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });

        btnEight.setBackground(new java.awt.Color(204, 204, 204));
        btnEight.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnEight.setText("8");
        btnEight.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });

        btnNine.setBackground(new java.awt.Color(204, 204, 204));
        btnNine.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnNine.setText("9");
        btnNine.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });

        btnDivisionOP.setBackground(new java.awt.Color(153, 153, 153));
        btnDivisionOP.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnDivisionOP.setText("/");
        btnDivisionOP.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnDivisionOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionOPActionPerformed(evt);
            }
        });

        btnMultiplicationOp.setBackground(new java.awt.Color(153, 153, 153));
        btnMultiplicationOp.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnMultiplicationOp.setText("*");
        btnMultiplicationOp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMultiplicationOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicationOpActionPerformed(evt);
            }
        });

        btnSubtractionOp.setBackground(new java.awt.Color(153, 153, 153));
        btnSubtractionOp.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnSubtractionOp.setText("-");
        btnSubtractionOp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSubtractionOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractionOpActionPerformed(evt);
            }
        });

        btnZero.setBackground(new java.awt.Color(204, 204, 204));
        btnZero.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnZero.setText("0");
        btnZero.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnDeciPoint.setBackground(new java.awt.Color(204, 204, 204));
        btnDeciPoint.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnDeciPoint.setText(".");
        btnDeciPoint.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnDeciPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeciPointActionPerformed(evt);
            }
        });

        btnEqualOp.setBackground(new java.awt.Color(102, 102, 102));
        btnEqualOp.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnEqualOp.setText("=");
        btnEqualOp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEqualOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualOpActionPerformed(evt);
            }
        });

        btnAdditionOp.setBackground(new java.awt.Color(153, 153, 153));
        btnAdditionOp.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnAdditionOp.setText("+");
        btnAdditionOp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAdditionOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdditionOpActionPerformed(evt);
            }
        });

        btnClearOp.setBackground(new java.awt.Color(102, 102, 102));
        btnClearOp.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnClearOp.setText("C");
        btnClearOp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnClearOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearOpActionPerformed(evt);
            }
        });

        btnDelOp.setBackground(new java.awt.Color(102, 102, 102));
        btnDelOp.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnDelOp.setText("Del");
        btnDelOp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnDelOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelOpActionPerformed(evt);
            }
        });

        btnOn.setText("On");
        btnOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnActionPerformed(evt);
            }
        });

        btnOff.setText("Off");
        btnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOffActionPerformed(evt);
            }
        });

        btnPlusMinus.setBackground(new java.awt.Color(102, 102, 102));
        btnPlusMinus.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnPlusMinus.setText("±");
        btnPlusMinus.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusMinusActionPerformed(evt);
            }
        });

        BacantoName.setText("Bacanto's Calculator 2.0");
        BacantoName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BacantoNameKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(BacantoName);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(screenDisplay)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDeciPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEqualOp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMultiplicationOp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSubtractionOp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdditionOp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDivisionOP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClearOp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelOp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(screenDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClearOp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelOp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDivisionOP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiplicationOp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubtractionOp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdditionOp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeciPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEqualOp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        // One Button
        String Enternumber = screenDisplay.getText() + btnOne.getText();
        screenDisplay.setText(Enternumber);
    }//GEN-LAST:event_btnOneActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        // Two Button
        String Enternumber = screenDisplay.getText() + btnTwo.getText();
        screenDisplay.setText(Enternumber);
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
        // Button Three
        String Enternumber = screenDisplay.getText() + btnThree.getText();
        screenDisplay.setText(Enternumber);
    }//GEN-LAST:event_btnThreeActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
        // Four Button
        String Enternumber = screenDisplay.getText() + btnFour.getText();
        screenDisplay.setText(Enternumber);
    }//GEN-LAST:event_btnFourActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        // Five Button
         String Enternumber = screenDisplay.getText() + btnFive.getText();
        screenDisplay.setText(Enternumber);
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
        // Six Button
         String Enternumber = screenDisplay.getText() + btnSix.getText();
        screenDisplay.setText(Enternumber);
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
        // Seven Button
        String Enternumber = screenDisplay.getText() + btnSeven.getText();
        screenDisplay.setText(Enternumber);
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
        // Eight Button
         String Enternumber = screenDisplay.getText() + btnEight.getText();
        screenDisplay.setText(Enternumber);
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
        // Nine Button
          String Enternumber = screenDisplay.getText() + btnNine.getText();
        screenDisplay.setText(Enternumber);
    }//GEN-LAST:event_btnNineActionPerformed

    private void btnDivisionOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionOPActionPerformed
        // Division Operation Button
         firstNum = Double.parseDouble(screenDisplay.getText());
        screenDisplay.setText("");
        operation = "/";
    }//GEN-LAST:event_btnDivisionOPActionPerformed

    private void btnMultiplicationOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicationOpActionPerformed
        // Multiplication Operation Button
        firstNum = Double.parseDouble(screenDisplay.getText());
        screenDisplay.setText("");
        operation = "*";
    }//GEN-LAST:event_btnMultiplicationOpActionPerformed

    private void btnSubtractionOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractionOpActionPerformed
        // Subtraction Operation Button
         firstNum = Double.parseDouble(screenDisplay.getText());
        screenDisplay.setText("");
        operation = "-";
    }//GEN-LAST:event_btnSubtractionOpActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        // Zero Button
        String Enternumber = screenDisplay.getText() + btnZero.getText();
        screenDisplay.setText(Enternumber);
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnDeciPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeciPointActionPerformed
        // Decimal Point Button    
        if (!screenDisplay.getText().contains(".")){
        screenDisplay.setText(screenDisplay.getText() + btnDeciPoint.getText());
    }//GEN-LAST:event_btnDeciPointActionPerformed
    }
    private void btnEqualOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualOpActionPerformed
        // Equal Operation Button
        String answer;
        secondNum = Double.parseDouble(screenDisplay.getText());
        
        if (operation == "+"){
            result = firstNum + secondNum;
            answer = String.format("%.2f", result);
            screenDisplay.setText(answer);
        }else if (operation == "-"){
            result = firstNum - secondNum;
            answer = String.format("%.2f", result);
            screenDisplay.setText(answer);
        }else if (operation == "/"){
            result = firstNum / secondNum;
            answer = String.format("%.2f", result);
            screenDisplay.setText(answer);
        }else if (operation == "*"){
            result = firstNum * secondNum;
            answer = String.format("%.2f", result);
            screenDisplay.setText(answer);
        }
    }//GEN-LAST:event_btnEqualOpActionPerformed

    private void btnAdditionOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdditionOpActionPerformed
        // Addition Operation Button
         firstNum = Double.parseDouble(screenDisplay.getText());
        screenDisplay.setText("");
        operation = "+";
    }//GEN-LAST:event_btnAdditionOpActionPerformed

    private void btnClearOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearOpActionPerformed
        // Clear Operation Button
          screenDisplay.setText("");
    }//GEN-LAST:event_btnClearOpActionPerformed

    private void screenDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screenDisplayActionPerformed
        // Screen Display
    }//GEN-LAST:event_screenDisplayActionPerformed

    private void btnDelOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelOpActionPerformed
        // Delete Operation Button
        String bsp = null;

        if(screenDisplay.getText().length()>0)
        {
            StringBuilder strB = new StringBuilder(screenDisplay.getText());
            strB.deleteCharAt(screenDisplay.getText().length() -1 );
            bsp = strB.toString();
            screenDisplay.setText(bsp);
        }
    }//GEN-LAST:event_btnDelOpActionPerformed

    private void btnOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnActionPerformed
        // On Button
        enable();
    }//GEN-LAST:event_btnOnActionPerformed

    private void btnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOffActionPerformed
        // Off Button
        screenDisplay.setText(null);
        disable();
    }//GEN-LAST:event_btnOffActionPerformed

    private void screenDisplayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_screenDisplayKeyTyped
        // TODO add your handling code here:
          char c=evt.getKeyChar();
         if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
        getToolkit().beep();
        evt.consume();
    }
    }//GEN-LAST:event_screenDisplayKeyTyped

    private void btnPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusMinusActionPerformed
        // Plus Minus Button
         double ops = Double.parseDouble(String.valueOf(screenDisplay.getText()));
        ops = ops *(-1);
        screenDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnPlusMinusActionPerformed

    private void BacantoNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BacantoNameKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
         if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
        getToolkit().beep();
        evt.consume();
    }//GEN-LAST:event_BacantoNameKeyTyped
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BCalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BCalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BCalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BCalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BCalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane BacantoName;
    private javax.swing.JButton btnAdditionOp;
    private javax.swing.JButton btnClearOp;
    private javax.swing.JButton btnDeciPoint;
    private javax.swing.JButton btnDelOp;
    private javax.swing.JButton btnDivisionOP;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEqualOp;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnMultiplicationOp;
    private javax.swing.JButton btnNine;
    private javax.swing.JRadioButton btnOff;
    private javax.swing.JRadioButton btnOn;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnPlusMinus;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnSubtractionOp;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField screenDisplay;
    // End of variables declaration//GEN-END:variables

    private Object getToolKit() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
